name: Build Job
on: 
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4.0.2
      with:
        node-version: '20.x'

    - name: Install dependencies
      run: npm install
      working-directory: ./box

    - name: Build
      run: npm run build
      working-directory: ./box

    - name: Deploy
      if: success()
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.ACTIONTOKEN }}
        publish_dir: ./box/dist/gh-pages

    - name: Clean up .angular/cache
      run: rm -rf .angular/cache
        
