name: Fetch leetcode scheduler
on:
  workflow_dispatch:
  schedule:
  - cron: '*/30 * * * *' 

jobs:
  fetch-leetcode:
    runs-on: ubuntu-latest

    permissions:    
      contents: write         
      pull-requests: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4.0.2
      with:
        node-version: '20.x'

    - name: Install dependencies
      run: npm install
      working-directory: ./scheduler/leetcode-stat

    - name: Run the script
      run: node app.js
      working-directory: ./scheduler/leetcode-stat
    
    - name: Configure Git
      run: |
        git config --global user.name "box-lin"
        git config --global user.email 'theboxlin@gmail.com'

    - name: Check for changes
      id: check_changes
      run: |
        git diff --exit-code || echo "::set-output name=changes::true"

    - name: Commit changes
      if: steps.check_changes.outputs.changes == 'true'
      run: |
        git add .
        git commit -m '[Bot] leetcode recent submissions JSON'

    - name: Push changes
      if: steps.check_changes.outputs.changes == 'true'
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.ACTIONTOKEN }}
        branch: main

    - name: Send out event
      if: steps.check_changes.outputs.changes == 'true'
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.ACTIONTOKEN }}
        event-type: fetch-leetcode-done
